% =========================================================================
% GENERATE SUPPLEMENTARY FIGURES — Chapter 4
% Produces: F4_9_VSM_Current.png  |  F4_10_VSM_Future.png
%           F4_11_Strategic_Roadmap.png
% (F4_1_N2_Diagram.png generated by n2_diagram.m)
%
% Visual design: NASA/Berkeley Earth data visualisation style
%   Grey background · Blue process boxes · Red highlights · Black text
%   Dashed grey grid · Clean sans-serif typography
% No toolboxes required.
% =========================================================================

clearvars; clc;

OUT = fullfile(fileparts(mfilename('fullpath')), 'figures');
if ~exist(OUT,'dir'), mkdir(OUT); end
fprintf('Output folder: %s\n\n', OUT);

% ── NASA colour palette ───────────────────────────────────────────────────
BG     = [0.941, 0.941, 0.941];   % light grey background
DBLUE  = [0.133, 0.133, 0.533];   % blue data / process elements
RTREND = [0.800, 0.000, 0.000];   % red highlights / warnings
BLACK  = [0.000, 0.000, 0.000];   % text, borders
DGRID  = [0.700, 0.700, 0.700];   % dashed grid
GREEN  = [0.000, 0.502, 0.000];   % improvement / optimised
ORANGE = [0.859, 0.322, 0.000];   % caution / ISRU
TEAL   = [0.000, 0.502, 0.502];   % pull signal
CISHD  = [0.600, 0.700, 0.900];   % blue shading fill
WBOX   = [1.000, 1.000, 1.000];   % white boxes

fprintf('Generating supplementary figures (NASA style)...\n');

%% ─────────────────────────────────────────────────────────────────────────
%% FIGURE F4.9 — VSM Current State  (NASA style)
%% ─────────────────────────────────────────────────────────────────────────
proc_names_c = {'Manifest &\newlinePlanning','Cargo\newlineIntegration', ...
    'Launch Prep\newline& Wait','Transit to\newlineGateway', ...
    'Docking &\newlineUnloading','Inventory\newlineStow & Issue', ...
    'Demand\newlineFulfillment'};
proc_ct_c = [14, 21, 30, 6, 3, 4, 5];
n_proc    = length(proc_ct_c);
box_w     = 0.82; box_h = 0.90;
tl_hi     = 1.00; tl_lo = 0.50;

fig = figure('Position',[100 100 1400 660],'Color',[1 1 1]);
ax  = axes(fig,'Color',BG); hold on; axis(ax,'off');
ax.XLim = [-0.8, n_proc+0.3]; ax.YLim = [-2.0, 5.2];

% Title (NASA large bold black title style)
text(ax,(n_proc-1)/2,5.05, ...
    'Current State Value Stream Map  (Baseline: 109-day Lead Time)', ...
    'HorizontalAlignment','center','FontSize',13,'FontWeight','bold','Color',BLACK);

% Supplier & Customer icons
for k = 1:2
    pos = (k-1)*(n_proc-1);
    lbl = 'Earth\newlineSupplier'; if k==2, lbl='Gateway\newlineCrew'; end
    tri_x = pos-0.15 + [0, 0.30, 0.15];
    fill(ax,tri_x,[2.5,2.5,3.0],'FaceColor',CISHD,'EdgeColor',BLACK,'LineWidth',1.5);
    text(ax,pos+0.0,2.35,lbl,'HorizontalAlignment','center', ...
        'FontSize',8,'FontWeight','bold','Color',BLACK);
end

% Process boxes — blue fill (NASA data-element colour)
for i = 1:n_proc
    x = i-1;
    % Box
    rectangle(ax,'Position',[x-box_w/2, 1.6, box_w, box_h], ...
        'Curvature',0.08,'FaceColor',CISHD,'EdgeColor',DBLUE,'LineWidth',2.0);
    text(ax,x,2.12,proc_names_c{i},'HorizontalAlignment','center', ...
        'FontSize',7.5,'FontWeight','bold','Color',BLACK);
    text(ax,x,1.73,sprintf('C/T: %d d',proc_ct_c(i)), ...
        'HorizontalAlignment','center','FontSize',7,'Color',BLACK);
    % Push arrows
    if i < n_proc
        annotation(fig,'arrow', ...
            [ax.Position(1)+(x+box_w/2+0.02)/range(ax.XLim)*ax.Position(3), ...
             ax.Position(1)+(x+0.50)/range(ax.XLim)*ax.Position(3)], ...
            [ax.Position(2)+2.08/range(ax.YLim)*ax.Position(4), ...
             ax.Position(2)+2.08/range(ax.YLim)*ax.Position(4)], ...
            'Color',RTREND,'LineWidth',2.0,'HeadLength',9,'HeadWidth',7);
        text(ax,x+0.50,2.22,'PUSH','HorizontalAlignment','center', ...
            'FontSize',6.5,'Color',RTREND,'FontWeight','bold');
    end
end

% Timeline zigzag (black line — NASA axis style)
xs=[]; ys=[];
for i=1:n_proc
    x=i-1; xs=[xs,x-box_w/2,x+box_w/2]; ys=[ys,tl_lo,tl_hi]; %#ok<AGROW>
end
xs=[xs,n_proc-1+box_w/2+0.1]; ys=[ys,tl_lo];
plot(ax,xs,ys,'-','Color',BLACK,'LineWidth',2.0);

% Cycle time labels — red (problem colour)
for i=1:n_proc
    text(ax,i-1,tl_lo-0.08,sprintf('%d d',proc_ct_c(i)), ...
        'HorizontalAlignment','center','FontSize',8,'Color',RTREND,'FontWeight','bold');
end

% Total lead time arrow (NASA double-arrow style)
annotation(fig,'doublearrow', ...
    [ax.Position(1)+(-box_w/2+0.8)/range(ax.XLim)*ax.Position(3), ...
     ax.Position(1)+(n_proc-1+box_w/2+0.8)/range(ax.XLim)*ax.Position(3)], ...
    repmat(ax.Position(2)+0.10/range(ax.YLim)*ax.Position(4),1,2), ...
    'Color',BLACK,'LineWidth',2.0,'HeadLength',10,'HeadWidth',8);
text(ax,(n_proc-1)/2,-0.02,'Total Lead Time = 109 days', ...
    'HorizontalAlignment','center','FontSize',10,'FontWeight','bold','Color',BLACK);

% KPI info-box (NASA annotation box style — white with border)
text(ax,(n_proc-1)/2,-0.72,'PCE = 21.1%          VA Time = 23 d          NVA Time = 86 d', ...
    'HorizontalAlignment','center','FontSize',10,'Color',BLACK, ...
    'BackgroundColor',WBOX,'EdgeColor',DGRID,'Margin',5,'LineWidth',1.5);

% Waste bursts — red circles (NASA warning style)
waste_x = [1.5, 2.5, 5.0];
waste_t = {'Overproduction:\newlineExcess manifest\newlinebatching', ...
           'Waiting:\newline30-day\newlinelaunch queue', ...
           'Inventory:\newlineUncontrolled\newlinestow cycles'};
for k=1:3
    th=linspace(0,2*pi,30);
    rx=0.24; ry=0.20;
    fill(ax,waste_x(k)+rx*cos(th),3.55+ry*sin(th), ...
        [1 0.95 0.80],'EdgeColor',RTREND,'LineWidth',2.5);
    text(ax,waste_x(k),3.18,waste_t{k},'HorizontalAlignment','center', ...
        'FontSize',6.5,'Color',RTREND,'FontWeight','bold');
end

% Data credit (NASA bottom-right style)
text(ax,n_proc-0.5,-1.60,'Gateway supply chain data | EG7302 MEM Individual Project (2025)', ...
    'HorizontalAlignment','right','FontSize',8,'Color',BLACK,'FontAngle','italic');

exportgraphics(fig, fullfile(OUT,'F4_9_VSM_Current.png'),'Resolution',300);
close(fig);
fprintf('F4.9 saved\n');

%% ─────────────────────────────────────────────────────────────────────────
%% FIGURE F4.10 — VSM Future State  (NASA style)
%% ─────────────────────────────────────────────────────────────────────────
proc_names_f = {'Integrated\newlinePlanning (AI)','Concurrent\newlineCargo Integ.', ...
    'Lean\newlineLaunch Prep','Transit to\newlineGateway', ...
    'Auto\newlineDocking','RFID-track\newlineStow','JIT\newlineFulfillment'};
proc_ct_f = [7, 10, 18, 6, 2, 2, 3];

fig = figure('Position',[100 100 1400 660],'Color',[1 1 1]);
ax  = axes(fig,'Color',BG); hold on; axis(ax,'off');
ax.XLim = [-0.8, n_proc+0.3]; ax.YLim = [-2.0, 5.2];

text(ax,(n_proc-1)/2,5.05, ...
    'Future State Value Stream Map  (Target: 75-day Lead Time, PCE 30.7%)', ...
    'HorizontalAlignment','center','FontSize',13,'FontWeight','bold','Color',BLACK);

% Supplier & Customer
for k=1:2
    pos=(k-1)*(n_proc-1);
    lbl='Earth\newlineSupplier'; if k==2, lbl='Gateway\newlineCrew'; end
    tri_x=pos-0.15+[0,0.30,0.15];
    fill(ax,tri_x,[2.5,2.5,3.0],'FaceColor',[0.80 0.95 0.80],'EdgeColor',GREEN,'LineWidth',1.5);
    text(ax,pos+0.0,2.35,lbl,'HorizontalAlignment','center', ...
        'FontSize',8,'FontWeight','bold','Color',BLACK);
end

% Process boxes — green fill (improved state)
for i=1:n_proc
    x=i-1;
    rectangle(ax,'Position',[x-box_w/2,1.6,box_w,box_h], ...
        'Curvature',0.08,'FaceColor',[0.88 0.96 0.88],'EdgeColor',GREEN,'LineWidth',2.2);
    text(ax,x,2.12,proc_names_f{i},'HorizontalAlignment','center', ...
        'FontSize',7.5,'FontWeight','bold','Color',BLACK);
    text(ax,x,1.73,sprintf('C/T: %d d',proc_ct_f(i)), ...
        'HorizontalAlignment','center','FontSize',7,'Color',BLACK);
    if i<n_proc
        % Pull arrow (reversed — TEAL colour for pull signal)
        annotation(fig,'arrow', ...
            [ax.Position(1)+(x+0.50)/range(ax.XLim)*ax.Position(3), ...
             ax.Position(1)+(x+box_w/2+0.02)/range(ax.XLim)*ax.Position(3)], ...
            [ax.Position(2)+2.08/range(ax.YLim)*ax.Position(4), ...
             ax.Position(2)+2.08/range(ax.YLim)*ax.Position(4)], ...
            'Color',TEAL,'LineWidth',2.0,'HeadLength',9,'HeadWidth',7);
    end
end

% Timeline — green line (improved state)
xs=[]; ys=[];
for i=1:n_proc
    x=i-1; xs=[xs,x-box_w/2,x+box_w/2]; ys=[ys,tl_lo,tl_hi]; %#ok<AGROW>
end
xs=[xs,n_proc-1+box_w/2+0.1]; ys=[ys,tl_lo];
plot(ax,xs,ys,'-','Color',GREEN,'LineWidth',2.5);

% CT labels — green (improved)
for i=1:n_proc
    text(ax,i-1,tl_lo-0.08,sprintf('%d d',proc_ct_f(i)), ...
        'HorizontalAlignment','center','FontSize',8,'Color',GREEN,'FontWeight','bold');
end

% Total lead time
annotation(fig,'doublearrow', ...
    [ax.Position(1)+(-box_w/2+0.8)/range(ax.XLim)*ax.Position(3), ...
     ax.Position(1)+(n_proc-1+box_w/2+0.8)/range(ax.XLim)*ax.Position(3)], ...
    repmat(ax.Position(2)+0.10/range(ax.YLim)*ax.Position(4),1,2), ...
    'Color',GREEN,'LineWidth',2.0,'HeadLength',10,'HeadWidth',8);
text(ax,(n_proc-1)/2,-0.02,'Total Lead Time = 75 days', ...
    'HorizontalAlignment','center','FontSize',10,'FontWeight','bold','Color',GREEN);

text(ax,(n_proc-1)/2,-0.72,'PCE = 30.7%          VA Time = 23 d          NVA Time = 52 d', ...
    'HorizontalAlignment','center','FontSize',10,'Color',BLACK, ...
    'BackgroundColor',WBOX,'EdgeColor',GREEN,'Margin',5,'LineWidth',1.5);

% PULL signal
text(ax,(n_proc-1)/2,0.30,'◄── PULL / JIT replenishment signal ──►', ...
    'HorizontalAlignment','center','FontSize',9,'Color',TEAL,'FontAngle','italic', ...
    'BackgroundColor',[0.90 0.98 0.98],'EdgeColor',TEAL,'Margin',4,'LineWidth',1);

% Kaizen starbursts — green (improvement events)
kaizen_x = [0, 1.5, 4.5];
kaizen_t = {'Kaizen:\newlineAI manifest\newlineoptimisation', ...
            'Kaizen:\newlineParallel\newlineCargo Integ.', ...
            'Kaizen:\newlineAutonomous\newlinedocking'};
for k=1:3
    th=linspace(0,2*pi,13);
    r_out=0.26; r_in=0.16;
    px=[]; py=[];
    for ii=1:12
        r=r_out*(mod(ii,2)==1)+r_in*(mod(ii,2)==0);
        px=[px,kaizen_x(k)+r*cos(th(ii))]; py=[py,3.55+r*sin(th(ii))]; %#ok<AGROW>
    end
    fill(ax,px,py,[0.88 0.96 0.88],'EdgeColor',GREEN,'LineWidth',2.0);
    text(ax,kaizen_x(k),3.18,kaizen_t{k},'HorizontalAlignment','center', ...
        'FontSize',6.5,'Color',GREEN,'FontWeight','bold');
end

text(ax,n_proc-0.5,-1.60,'Gateway supply chain data | EG7302 MEM Individual Project (2025)', ...
    'HorizontalAlignment','right','FontSize',8,'Color',BLACK,'FontAngle','italic');

exportgraphics(fig, fullfile(OUT,'F4_10_VSM_Future.png'),'Resolution',300);
close(fig);
fprintf('F4.10 saved\n');

%% ─────────────────────────────────────────────────────────────────────────
%% FIGURE F4.11 — Strategic Roadmap  (NASA style)
%% ─────────────────────────────────────────────────────────────────────────
fig = figure('Position',[100 100 1500 820],'Color',[1 1 1]);
ax  = axes(fig,'Color',BG); hold on; axis(ax,'off');
ax.XLim=[0,15]; ax.YLim=[0,8.5];

% Large bold title (NASA style)
text(ax,7.5,8.30,'Lunar Gateway Supply Chain Strategic Roadmap  (2026–2035)', ...
    'HorizontalAlignment','center','FontSize',14,'FontWeight','bold','Color',BLACK);

% Phase bands — blue/green/orange/red (NASA cool-to-warm palette)
phases = {
    'Phase 0\newlineFoundation\newline2026–2027',   0.2, 3.8, CISHD,            DBLUE;
    'Phase 1\newlineOptimisation\newline2028–2030',  4.0, 8.3, [0.82 0.94 0.82], GREEN;
    'Phase 2\newlineAutonomy\newline2031–2033',       8.5,12.3, [1.00 0.94 0.80], ORANGE;
    'Phase 3\newlineSustainability\newline2034–2035',12.5,14.8, [1.00 0.87 0.87], RTREND;
};
for i=1:size(phases,1)
    x0=phases{i,2}; x1=phases{i,3}; fc=phases{i,4}; ec=phases{i,5};
    rectangle(ax,'Position',[x0,6.1,x1-x0,1.3], ...
        'Curvature',0.04,'FaceColor',fc,'EdgeColor',ec,'LineWidth',2.0);
    text(ax,(x0+x1)/2,6.75,phases{i,1},'HorizontalAlignment','center', ...
        'FontSize',9.5,'FontWeight','bold','Color',ec);
end

% Timeline arrow — black (NASA axis arrow)
annotation(fig,'arrow',[0.06 0.97],[0.455 0.455], ...
    'Color',BLACK,'LineWidth',2.5,'HeadLength',14,'HeadWidth',10);
text(ax,7.5,5.42,'Timeline  →','HorizontalAlignment','center', ...
    'FontSize',10,'Color',BLACK,'FontAngle','italic');

% Year tick marks — black (NASA axis ticks)
for yr=2026:2035
    x=(yr-2026)/9*14.6+0.2;
    plot(ax,[x x],[5.52 5.64],'-','Color',BLACK,'LineWidth',1.5);
    text(ax,x,5.46,num2str(yr),'HorizontalAlignment','center', ...
        'FontSize',8,'Color',BLACK,'FontWeight','bold');
end

% Swim lanes — coloured fills (NASA panel layout)
lanes = {
    'Cost Management',   DBLUE,  5.10;
    'Logistics & MILP',  GREEN,  4.10;
    'ISRU Integration',  ORANGE, 3.10;
    'Risk & Resilience', RTREND, 2.10;
};
for k=1:4
    clr=lanes{k,2}; y_top=lanes{k,3};
    rectangle(ax,'Position',[0.2,y_top-0.82,14.6,0.82], ...
        'Curvature',0.02,'FaceColor',[clr,0.10],'EdgeColor',clr,'LineWidth',1.5,'FaceAlpha',0.15);
    % Lane label with white background (NASA label box)
    text(ax,0.10,y_top-0.41,lanes{k,1},'FontSize',8.5,'FontWeight','bold','Color',clr, ...
        'VerticalAlignment','middle','BackgroundColor','white','EdgeColor',clr,'Margin',2);
end

% Milestones — black filled diamond + colored label (NASA data-point style)
MS_data = {
    % Cost Management  y~4.70
    1.0,4.70,'CER baseline\ncalibrated',       DBLUE;
    3.0,4.70,'MILP v1\ndeployed',               DBLUE;
    6.0,4.70,'Dynamic CER\nupdates',            DBLUE;
   10.5,4.70,'Autonomous\nbudget opt.',          DBLUE;
   13.5,4.70,'$225M saving\nlocked',            DBLUE;
    % Logistics  y~3.70
    2.0,3.70,'Safety stock\nSS=193 kg',         GREEN;
    5.5,3.70,'Multi-provider\n11 missions',      GREEN;
    8.0,3.70,'JIT pull\nsystem live',           GREEN;
   12.0,3.70,'Autonomous\nreplenishment',        GREEN;
    % ISRU  y~2.70
    4.0,2.70,'ISRU pilot\ncommission',           ORANGE;
    7.5,2.70,'H2O yield\n+15% target',          ORANGE;
   11.0,2.70,'ISRU NPV\n+$32M break-even',      ORANGE;
   14.0,2.70,'Full ISRU\nautonomous',            ORANGE;
    % Risk  y~1.70
    1.5,1.70,'FMEA baseline\n(RPN<120)',         RTREND;
    5.0,1.70,'Redundancy\nC-7 active',           RTREND;
    9.0,1.70,'AI anomaly\ndetection',            RTREND;
   13.0,1.70,'Risk P90\n<$1,820M',              RTREND;
};

for m=1:size(MS_data,1)
    xm=MS_data{m,1}; ym=MS_data{m,2}; clr=MS_data{m,4};
    % Diamond — black fill (NASA data point)
    dx=0.13; dy=0.19;
    fill(ax,[xm,xm+dx,xm,xm-dx],[ym+dy,ym,ym-dy,ym], ...
        BLACK,'EdgeColor',WBOX,'LineWidth',0.8);
    % Colored label below
    text(ax,xm,ym-0.25,MS_data{m,3}, ...
        'HorizontalAlignment','center','FontSize',5.5,'Color',clr, ...
        'VerticalAlignment','top','FontWeight','bold');
end

% Legend (NASA info-box style)
leg_items = {'Phase 0: Foundation','Phase 1: Optimisation','Phase 2: Autonomy','Phase 3: Sustainability'};
leg_fc    = {CISHD,[0.82 0.94 0.82],[1.00 0.94 0.80],[1.00 0.87 0.87]};
leg_ec    = {DBLUE, GREEN, ORANGE, RTREND};
for k=1:4
    rectangle(ax,'Position',[0.2+(k-1)*3.55, 1.00, 0.42, 0.30], ...
        'FaceColor',leg_fc{k},'EdgeColor',leg_ec{k},'LineWidth',1.5);
    text(ax,0.72+(k-1)*3.55, 1.15, leg_items{k}, ...
        'FontSize',8.5,'Color',leg_ec{k},'VerticalAlignment','middle','FontWeight','bold');
end

% Credit (NASA bottom-right)
text(ax,14.9,0.12,'Source: Author (2025)  |  EG7302 MEM Individual Project  |  Data: NASA/GAO', ...
    'HorizontalAlignment','right','FontSize',8,'Color',BLACK,'FontAngle','italic');

exportgraphics(fig, fullfile(OUT,'F4_11_Strategic_Roadmap.png'),'Resolution',300);
close(fig);
fprintf('F4.11 saved\n');

fprintf('\nAll supplementary figures generated (NASA style).\n');
